export const siteConfig = {
  brand: {
    name: "Montalvão & Prado",
    shortName: "M&P",
    registration: "OAB/SP 00.000",
    descriptor: "Advocacia Empresarial Estratégica",
    slogan: "Decisões seguras. Negócios protegidos.",
  },
  colors: {
    primary: "#153B4F",
    secondary: "#B18A52",
    dark: "#0F172A",
    surface: "#F8FAFC",
  },
  contact: {
    whatsapp: "5511999999999",
    whatsappDisplay: "+55 11 99999-9999",
    whatsappMessage: "Olá, gostaria de agendar uma análise estratégica com a equipe.",
    email: "contato@montalvaoepardo.com.br",
    address: "Av. Brigadeiro Faria Lima, 3.477, São Paulo, SP",
    hours: "Segunda a sexta, das 9h às 18h",
  },
  social: {
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
  },
  navigation: [
    { label: "Atuação", href: "#atuacao" },
    { label: "Método", href: "#metodo" },
    { label: "Resultados", href: "#resultados" },
    { label: "FAQ", href: "#faq" },
  ],
  labels: {
    headerCta: "Falar com especialista",
    goToStart: "Ir para o início",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    heroCardEyebrow: "Análise estratégica",
    heroCardDescription: "Atendimento empresarial personalizado",
    heroCardCta: "Agendar conversa confidencial",
    stars: "5 de 5 estrelas",
    footerNavigation: "Navegação",
    footerContact: "Contato",
    formNamePlaceholder: "Seu nome",
    formPhonePlaceholder: "(11) 99999-9999",
    formCompanyPlaceholder: "Nome da empresa",
    formSelectPlaceholder: "Selecione uma opção",
    formMessagePlaceholder: "Descreva em poucas linhas",
    formError: "Preencha nome, WhatsApp e tema, e aceite o aviso de privacidade.",
  },
  hero: {
    eyebrow: "Estratégia jurídica para empresas que não podem parar",
    title: "Transformamos complexidade jurídica em",
    highlight: "decisões seguras.",
    description: "Assessoria empresarial próxima, técnica e orientada a resultados para líderes que precisam avançar com previsibilidade.",
    primaryCta: "Falar com um especialista",
    secondaryCta: "Conhecer nossa atuação",
    note: "Atendimento inicial confidencial e sem compromisso.",
    highlights: [
      "Resposta ágil e acompanhamento próximo",
      "Estratégia sob medida para cada cenário",
      "Visão jurídica integrada ao seu negócio",
    ],
    metrics: [
      { value: "+12", label: "anos de experiência" },
      { value: "+480", label: "casos conduzidos" },
      { value: "92%", label: "de clientes recorrentes" },
    ],
  },
  trust: {
    eyebrow: "Confiança construída na prática",
    items: [
      { title: "Sigilo absoluto", description: "Informações tratadas com rigor" },
      { title: "Atuação nacional", description: "Suporte onde sua empresa estiver" },
      { title: "Visão de negócio", description: "Jurídico conectado à estratégia" },
      { title: "Comunicação clara", description: "Sem juridiquês desnecessário" },
    ],
  },
  situation: {
    eyebrow: "O custo de adiar decisões importantes",
    title: "Você não precisa escolher entre crescer e se proteger.",
    description: "Empresas maduras tratam o jurídico como inteligência de negócio antes que riscos silenciosos se tornem urgências caras.",
    currentTitle: "Sua situação atual",
    solutionTitle: "Com nossa assessoria",
    current: [
      "Decisões importantes tomadas sem clareza dos riscos",
      "Contratos genéricos que deixam brechas e insegurança",
      "Demandas jurídicas fragmentadas entre diferentes profissionais",
      "Tempo da liderança consumido por problemas evitáveis",
    ],
    solution: [
      "Cenários traduzidos em recomendações objetivas",
      "Contratos desenhados para a realidade da operação",
      "Visão integrada, preventiva e centralizada",
      "Liderança focada no negócio, com respaldo contínuo",
    ],
  },
  services: {
    eyebrow: "Áreas de atuação",
    title: "Proteção jurídica em cada decisão relevante.",
    description: "Uma equipe sênior para estruturar, prevenir e conduzir os temas que afetam o valor e a continuidade da sua empresa.",
    items: [
      { icon: "building", title: "Societário & Governança", description: "Estruturas societárias, acordos, reorganizações e governança para relações mais seguras.", detail: "Estruture para crescer" },
      { icon: "file", title: "Contratos Estratégicos", description: "Negociação e revisão de contratos críticos com foco em clareza, proteção e equilíbrio.", detail: "Negocie com segurança" },
      { icon: "shield", title: "Prevenção de Riscos", description: "Diagnóstico jurídico e planos de ação que antecipam passivos antes que eles escalem.", detail: "Antecipe cenários" },
      { icon: "scale", title: "Contencioso Complexo", description: "Condução técnica de disputas relevantes com estratégia, precisão e visão de impacto.", detail: "Defenda seus interesses" },
      { icon: "users", title: "Relações de Trabalho", description: "Apoio preventivo e contencioso para decisões trabalhistas alinhadas à operação.", detail: "Proteja suas relações" },
      { icon: "lock", title: "Proteção de Dados", description: "Adequação à LGPD, governança de dados e resposta estratégica a incidentes.", detail: "Fortaleça a confiança" },
    ],
  },
  founder: {
    eyebrow: "Liderança presente em cada estratégia",
    name: "Dra. Helena Montalvão",
    role: "Sócia-fundadora • OAB/SP 00.000",
    image: "/ceo.jpg",
    imageAlt: "Profissional em ambiente corporativo",
    quote: "Nosso trabalho começa entendendo o negócio. Só então o Direito se transforma em uma ferramenta real de decisão.",
    bio: [
      "Há mais de 12 anos, Helena assessora empresários, conselhos e executivos em decisões de alta complexidade, unindo rigor técnico a uma comunicação direta.",
      "Sua atuação é reconhecida pela capacidade de enxergar o problema jurídico dentro do contexto comercial, preservando relações, reputação e valor.",
    ],
    credentials: [
      "Especialista em Direito Empresarial",
      "Membro do Instituto Brasileiro de Direito Empresarial",
      "Conselheira de empresas familiares e scale-ups",
    ],
  },
  methodology: {
    eyebrow: "Como funciona",
    title: "Clareza do primeiro contato à decisão final.",
    description: "Um processo simples, próximo e estruturado para reduzir incertezas e acelerar respostas.",
    steps: [
      { number: "01", title: "Escuta e diagnóstico", description: "Entendemos o contexto, as prioridades e o impacto real da situação para o negócio." },
      { number: "02", title: "Estratégia objetiva", description: "Apresentamos cenários, riscos e uma recomendação clara, sem respostas genéricas." },
      { number: "03", title: "Execução próxima", description: "Conduzimos cada frente com transparência, cadência e acesso direto à equipe responsável." },
      { number: "04", title: "Acompanhamento", description: "Monitoramos desdobramentos e antecipamos ajustes para manter a estratégia protegida." },
    ],
  },
  testimonials: {
    eyebrow: "Resultados que sustentam relações",
    title: "Confiança de quem precisa decidir bem.",
    items: [
      { quote: "A equipe entendeu nossa operação rapidamente e transformou um tema complexo em um plano claro. Hoje tomamos decisões com outro nível de segurança.", author: "Ricardo A.", role: "CEO, empresa de tecnologia B2B", result: "Reestruturação societária concluída em 60 dias" },
      { quote: "Encontramos uma assessoria que fala a língua do negócio. A proximidade e a previsibilidade mudaram completamente nossa relação com o jurídico.", author: "Marina S.", role: "Diretora, grupo de saúde", result: "Redução de 38% em contingências contratuais" },
      { quote: "Mais do que resolver a urgência, o escritório reorganizou nossas práticas para que o problema não voltasse a acontecer.", author: "André P.", role: "Sócio, consultoria executiva", result: "Novo modelo preventivo implantado em 3 unidades" },
    ],
    disclaimer: "Depoimentos ilustrativos para fins de demonstração deste template.",
  },
  faq: {
    eyebrow: "Perguntas frequentes",
    title: "O que você precisa saber antes de conversar conosco.",
    items: [
      { question: "Como funciona a primeira conversa?", answer: "É uma reunião confidencial para entendermos o contexto, a urgência e o impacto do tema. A partir dela, indicamos o melhor formato de atuação e os próximos passos." },
      { question: "Vocês atendem empresas fora de São Paulo?", answer: "Sim. Atendemos empresas em todo o Brasil por videoconferência e, quando necessário, organizamos encontros presenciais e atuação local com parceiros homologados." },
      { question: "Quais são os formatos de contratação?", answer: "Trabalhamos com projetos de escopo fechado, assessoria recorrente e modelos híbridos. A proposta é definida conforme a complexidade, a previsibilidade e o nível de acompanhamento necessário." },
      { question: "Em quanto tempo recebo um retorno?", answer: "Novos contatos recebem um retorno inicial em até um dia útil. Demandas urgentes são sinalizadas e avaliadas com prioridade pela equipe." },
      { question: "Meu contato e minhas informações são confidenciais?", answer: "Sim. Toda comunicação é tratada sob sigilo profissional desde o primeiro contato, mesmo antes da formalização da contratação." },
    ],
  },
  conversion: {
    eyebrow: "Conversa estratégica",
    title: "Seu próximo passo pode começar com mais clareza.",
    description: "Conte brevemente o que precisa resolver. Nossa equipe fará um primeiro contato pelo WhatsApp em até um dia útil.",
    fields: {
      name: "Como podemos chamar você?",
      phone: "Seu WhatsApp",
      company: "Empresa (opcional)",
      service: "Tema principal",
      message: "Conte brevemente o seu cenário (opcional)",
      privacy: "Autorizo o contato e declaro que li o aviso de privacidade.",
    },
    options: ["Societário & Governança", "Contratos Estratégicos", "Prevenção de Riscos", "Contencioso Complexo", "Relações de Trabalho", "Proteção de Dados", "Outro tema"],
    button: "Solicitar análise pelo WhatsApp",
    reassurance: "Sem compromisso • Dados protegidos • Resposta em até 1 dia útil",
  },
  footer: {
    description: "Assessoria jurídica empresarial para decisões seguras, relações protegidas e crescimento sustentável.",
    cta: "Falar com especialista",
    legal: "Este site possui caráter exclusivamente informativo e não substitui aconselhamento jurídico individualizado. O envio do formulário não estabelece relação advogado-cliente.",
    privacyTitle: "Aviso de privacidade",
    privacyText: "Os dados enviados são utilizados exclusivamente para responder ao seu contato e avaliar a demanda apresentada. Não comercializamos informações pessoais. Você pode solicitar correção ou exclusão pelo e-mail informado nesta página.",
    termsTitle: "Termos de uso",
    termsText: "O conteúdo desta página é informativo, pode ser atualizado sem aviso prévio e não constitui promessa de resultado. Marcas e exemplos apresentados neste template devem ser substituídos antes da publicação comercial.",
    copyright: "Todos os direitos reservados.",
  },
} as const;

export type SiteConfig = typeof siteConfig;
